[workspace]
members = [
  "model",
  "server",
  "client"
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["Adel Ayoub"]
description = "A secure distributed file system"
